# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleClick' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for SampleClick
  pod 'SwiftySound'
end
